package com.kalah.Kalah;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import lombok.extern.slf4j.Slf4j;

@Slf4j
@Component
public class RestDatabaseInitializer implements CommandLineRunner {
	@Autowired
	private PositionsRepository positionsRepository;
	@Autowired
	private MovesRepository movesRepository;
	
	@Override
	public void run(String...args) throws Exception{
		//log.info("Starting to initialize sample data...");
			Positions positions = new Positions();
			positions.setId(Long.valueOf(1));
			positions.setPosition("start");
			positions.setLsl(0);
			positions.setLl(0);
			positions.setAst(3);
			positions.setAt(0);
			positions.setBst(3);
			positions.setBt(0);
			positions.setCst(3);
			positions.setCt(0);
			positions.setDst(3);
			positions.setDt(0);
			positions.setEst(3);
			positions.setEt(0);
			positions.setFst(3);
			positions.setFt(0);
			positions.setLr(0);
			positions.setLsr(0);
			positions.setAsb(0);
			positions.setAb(3);
			positions.setBsb(0);
			positions.setBb(3);
			positions.setCsb(0);
			positions.setCb(3);
			positions.setDsb(0);
			positions.setDb(3);
			positions.setEsb(0);
			positions.setEb(3);
			positions.setFsb(0);
			positions.setFb(3);
			positionsRepository.save(positions);
			Integer i = 0;
			Moves moves = new Moves();
			moves.setId(Long.valueOf(i));
			i++;
			moves.setMoves("a");
			moves.setClassSet(".threePiecesBg-b");
			moves.setNumberPieces(1);
			movesRepository.save(moves);
			Moves moves100 = new Moves();
			moves100.setId(Long.valueOf(i));
			i++;
			moves100.setMoves("a");
			moves100.setClassSet(".threePiecesBg-b");
			moves100.setNumberPieces(1);
			movesRepository.save(moves100);
			Moves moves0 = new Moves();
			moves0.setId(Long.valueOf(i));
			i++;
			moves0.setMoves("a");
			moves0.setClassSet(".threePiecesBg-b");
			moves0.setNumberPieces(1);
			movesRepository.save(moves0);
			Moves moves1 = new Moves();
			moves1.setId(Long.valueOf(i));
			i++;
			moves1.setMoves("a");
			moves1.setClassSet(".threePiecesBg-b,.threePiecesBg-c");
			moves1.setNumberPieces(2);
			movesRepository.save(moves1);
			Moves moves2 = new Moves();
			moves2.setId(Long.valueOf(i));
			i++;
			moves2.setMoves("a");
			moves2.setClassSet(".threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d");
			moves2.setNumberPieces(3);
			movesRepository.save(moves2);
			Moves moves3 = new Moves();
			moves3.setId(Long.valueOf(i));
			i++;
			moves3.setMoves("a");
			moves3.setClassSet(".threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e");
			moves3.setNumberPieces(4);
			movesRepository.save(moves3);
			Moves moves4 = new Moves();
			moves4.setId(Long.valueOf(i));
			i++;
			moves4.setMoves("a");
			moves4.setClassSet(".threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f");
			moves4.setNumberPieces(5);
			movesRepository.save(moves4);
			Moves moves5 = new Moves();
			moves5.setId(Long.valueOf(i));
			i++;
			moves5.setMoves("a");
			moves5.setClassSet(".threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom");
			moves5.setNumberPieces(6);
			movesRepository.save(moves5);
			Moves moves6 = new Moves();
			moves6.setId(Long.valueOf(i));
			i++;
			moves6.setMoves("a");
			moves6.setClassSet(".threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f");
			moves6.setNumberPieces(7);
			movesRepository.save(moves6);
			Moves moves7 = new Moves();
			moves7.setId(Long.valueOf(i));
			i++;
			moves7.setMoves("b");
			moves7.setClassSet(".threePiecesBg-c");
			moves7.setNumberPieces(1);
			movesRepository.save(moves7);
			Moves moves8 = new Moves();
			moves8.setId(Long.valueOf(i));
			i++;
			moves8.setMoves("b");
			moves8.setClassSet(".threePiecesBg-c,.threePiecesBg-d");
			moves8.setNumberPieces(2);
			movesRepository.save(moves8);
			Moves moves9 = new Moves();
			moves9.setId(Long.valueOf(i));
			i++;
			moves9.setMoves("b");
			moves9.setClassSet(".threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e");
			moves9.setNumberPieces(3);
			movesRepository.save(moves9);
			Moves moves10 = new Moves();
			moves10.setId(Long.valueOf(i));
			i++;
			moves10.setMoves("b");
			moves10.setClassSet(".threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f");
			moves10.setNumberPieces(4);
			movesRepository.save(moves10);
			Moves moves11 = new Moves();
			moves11.setId(Long.valueOf(i));
			i++;
			moves11.setMoves("b");
			moves11.setClassSet(".threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom");
			moves11.setNumberPieces(5);
			movesRepository.save(moves11);
			Moves moves12 = new Moves();
			moves12.setId(Long.valueOf(i));
			i++;
			moves12.setMoves("b");
			moves12.setClassSet(".threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f");
			moves12.setNumberPieces(6);
			movesRepository.save(moves12);
			Moves moves13 = new Moves();
			moves13.setId(Long.valueOf(i));
			i++;
			moves13.setMoves("b");
			moves13.setClassSet(".threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e");
			moves13.setNumberPieces(7);
			movesRepository.save(moves13);
			Moves moves14 = new Moves();
			moves14.setId(Long.valueOf(i));
			i++;
			moves14.setMoves("c");
			moves14.setClassSet(".threePiecesBg-d");
			moves14.setNumberPieces(1);
			movesRepository.save(moves14);
			Moves moves15 = new Moves();
			moves15.setId(Long.valueOf(i));
			i++;
			moves15.setMoves("c");
			moves15.setClassSet(".threePiecesBg-d,.threePiecesBg-e");
			moves15.setNumberPieces(2);
			movesRepository.save(moves15);
			Moves moves16 = new Moves();
			moves16.setId(Long.valueOf(i));
			i++;
			moves16.setMoves("c");
			moves16.setClassSet(".threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f");
			moves16.setNumberPieces(3);
			movesRepository.save(moves16);
			Moves moves17 = new Moves();
			moves17.setId(Long.valueOf(i));
			i++;
			moves17.setMoves("c");
			moves17.setClassSet(".threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom");
			moves17.setNumberPieces(4);
			movesRepository.save(moves17);
			Moves moves18 = new Moves();
			moves18.setId(Long.valueOf(i));
			i++;
			moves18.setMoves("c");
			moves18.setClassSet(".threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f");
			moves18.setNumberPieces(5);
			movesRepository.save(moves18);
			Moves moves19 = new Moves();
			moves19.setId(Long.valueOf(i));
			i++;
			moves19.setMoves("c");
			moves19.setClassSet(".threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e");
			moves19.setNumberPieces(6);
			movesRepository.save(moves19);
			Moves moves20 = new Moves();
			moves20.setId(Long.valueOf(i));
			i++;
			moves20.setMoves("c");
			moves20.setClassSet(".threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d");
			moves20.setNumberPieces(7);
			movesRepository.save(moves20);
			Moves moves21 = new Moves();
			moves21.setId(Long.valueOf(i));
			i++;
			moves21.setMoves("d");
			moves21.setClassSet(".threePiecesBg-e");
			moves21.setNumberPieces(1);
			movesRepository.save(moves21);
			Moves moves22 = new Moves();
			moves22.setId(Long.valueOf(i));
			i++;
			moves22.setMoves("d");
			moves22.setClassSet(".threePiecesBg-e,.threePiecesBg-f");
			moves22.setNumberPieces(2);
			movesRepository.save(moves22);
			Moves moves23 = new Moves();
			moves23.setId(Long.valueOf(i));
			i++;
			moves23.setMoves("d");
			moves23.setClassSet(".threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom");
			moves23.setNumberPieces(3);
			movesRepository.save(moves23);
			Moves moves24 = new Moves();
			moves24.setId(Long.valueOf(i));
			i++;
			moves24.setMoves("d");
			moves24.setClassSet(".threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f");
			moves24.setNumberPieces(4);
			movesRepository.save(moves24);
			Moves moves25 = new Moves();
			moves25.setId(Long.valueOf(i));
			i++;
			moves25.setMoves("d");
			moves25.setClassSet(".threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e");
			moves25.setNumberPieces(5);
			movesRepository.save(moves25);
			Moves moves26 = new Moves();
			moves26.setId(Long.valueOf(i));
			i++;
			moves26.setMoves("d");
			moves26.setClassSet(".threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d");
			moves26.setNumberPieces(6);
			movesRepository.save(moves26);
			Moves moves27 = new Moves();
			moves27.setId(Long.valueOf(i));
			i++;
			moves27.setMoves("d");
			moves27.setClassSet(".threePiecesBg-e,.threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c");
			moves27.setNumberPieces(7);
			movesRepository.save(moves27);
			Moves moves28 = new Moves();
			moves28.setId(Long.valueOf(i));
			i++;
			moves28.setMoves("e");
			moves28.setClassSet(".threePiecesBg-f");
			moves28.setNumberPieces(1);
			movesRepository.save(moves28);
			Moves moves29 = new Moves();
			moves29.setId(Long.valueOf(i));
			i++;
			moves29.setMoves("e");
			moves29.setClassSet(".threePiecesBg-f,.threePiecesOg-f.bottom");
			moves29.setNumberPieces(2);
			movesRepository.save(moves29);
			Moves moves30 = new Moves();
			moves30.setId(Long.valueOf(i));
			i++;
			moves30.setMoves("e");
			moves30.setClassSet(".threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f");
			moves30.setNumberPieces(3);
			movesRepository.save(moves30);
			Moves moves31 = new Moves();
			moves31.setId(Long.valueOf(i));
			i++;
			moves31.setMoves("e");
			moves31.setClassSet(".threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e");
			moves31.setNumberPieces(4);
			movesRepository.save(moves31);
			Moves moves32 = new Moves();
			moves32.setId(Long.valueOf(i));
			i++;
			moves32.setMoves("e");
			moves32.setClassSet(".threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d");
			moves32.setNumberPieces(5);
			movesRepository.save(moves32);
			Moves moves33 = new Moves();
			moves33.setId(Long.valueOf(i));
			i++;
			moves33.setMoves("e");
			moves33.setClassSet(".threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c");
			moves33.setNumberPieces(6);
			movesRepository.save(moves33);
			Moves moves34 = new Moves();
			moves34.setId(Long.valueOf(i));
			i++;
			moves34.setMoves("e");
			moves34.setClassSet(".threePiecesBg-f,.threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b");
			moves34.setNumberPieces(7);
			movesRepository.save(moves34);
			Moves moves35 = new Moves();
			moves35.setId(Long.valueOf(i));
			i++;
			moves35.setMoves("f");
			moves35.setClassSet(".threePiecesOg-f.bottom");
			moves35.setNumberPieces(1);
			movesRepository.save(moves35);
			Moves moves36 = new Moves();
			moves36.setId(Long.valueOf(i));
			i++;
			moves36.setMoves("f");
			moves36.setClassSet(".threePiecesOg-f.bottom,.threePiecesSg-f");
			moves36.setNumberPieces(2);
			movesRepository.save(moves36);
			Moves moves37 = new Moves();
			moves37.setId(Long.valueOf(i));
			i++;
			moves37.setMoves("f");
			moves37.setClassSet(".threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e");
			moves37.setNumberPieces(3);
			movesRepository.save(moves37);
			Moves moves38 = new Moves();
			moves38.setId(Long.valueOf(i));
			i++;
			moves38.setMoves("f");
			moves38.setClassSet(".threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d");
			moves38.setNumberPieces(4);
			movesRepository.save(moves38);
			Moves moves39 = new Moves();
			moves39.setId(Long.valueOf(i));
			i++;
			moves39.setMoves("f");
			moves39.setClassSet(".threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c");
			moves39.setNumberPieces(5);
			movesRepository.save(moves39);
			Moves moves40 = new Moves();
			moves40.setId(Long.valueOf(i));
			i++;
			moves40.setMoves("f");
			moves40.setClassSet(".threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b");
			moves40.setNumberPieces(6);
			movesRepository.save(moves40);
			Moves moves41 = new Moves();
			moves41.setId(Long.valueOf(i));
			i++;
			moves41.setMoves("f");
			moves41.setClassSet(".threePiecesOg-f.bottom,.threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a");
			moves41.setNumberPieces(7);
			movesRepository.save(moves41);
			Moves moves42 = new Moves();
			moves42.setId(Long.valueOf(i));
			i++;
			moves42.setMoves("l");
			moves42.setClassSet(".threePiecesSg-f");
			moves42.setNumberPieces(1);
			movesRepository.save(moves42);
			Moves moves43 = new Moves();
			moves43.setId(Long.valueOf(i));
			i++;
			moves43.setMoves("l");
			moves43.setClassSet(".threePiecesSg-f,.threePiecesSg-e");
			moves43.setNumberPieces(2);
			movesRepository.save(moves43);
			Moves moves44 = new Moves();
			moves44.setId(Long.valueOf(i));
			i++;
			moves44.setMoves("l");
			moves44.setClassSet(".threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d");
			moves44.setNumberPieces(3);
			movesRepository.save(moves44);
			Moves moves45 = new Moves();
			moves45.setId(Long.valueOf(i));
			i++;
			moves45.setMoves("l");
			moves45.setClassSet(".threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c");
			moves45.setNumberPieces(4);
			movesRepository.save(moves45);
			Moves moves46 = new Moves();
			moves46.setId(Long.valueOf(i));
			i++;
			moves46.setMoves("l");
			moves46.setClassSet(".threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b");
			moves46.setNumberPieces(5);
			movesRepository.save(moves46);
			Moves moves47 = new Moves();
			moves47.setId(Long.valueOf(i));
			i++;
			moves47.setMoves("l");
			moves47.setClassSet(".threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a");
			moves47.setNumberPieces(6);
			movesRepository.save(moves47);
			Moves moves48 = new Moves();
			moves48.setId(Long.valueOf(i));
			i++;
			moves48.setMoves("l");
			moves48.setClassSet(".threePiecesSg-f,.threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom");
			moves48.setNumberPieces(7);
			movesRepository.save(moves48);
			Moves moves49 = new Moves();
			moves49.setId(Long.valueOf(i));
			i++;
			moves49.setMoves("fb");
			moves49.setClassSet(".threePiecesSg-e");
			moves49.setNumberPieces(1);
			movesRepository.save(moves49);
			Moves moves50 = new Moves();
			moves50.setId(Long.valueOf(i));
			i++;
			moves50.setMoves("fb");
			moves50.setClassSet(".threePiecesSg-e,.threePiecesSg-d");
			moves50.setNumberPieces(2);
			movesRepository.save(moves50);
			Moves moves51 = new Moves();
			moves51.setId(Long.valueOf(i));
			i++;
			moves51.setMoves("fb");
			moves51.setClassSet(".threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c");
			moves51.setNumberPieces(3);
			movesRepository.save(moves51);
			Moves moves52 = new Moves();
			moves52.setId(Long.valueOf(i));
			i++;
			moves52.setMoves("fb");
			moves52.setClassSet(".threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b");
			moves52.setNumberPieces(4);
			movesRepository.save(moves52);
			Moves moves53 = new Moves();
			moves53.setId(Long.valueOf(i));
			i++;
			moves53.setMoves("fb");
			moves53.setClassSet(".threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a");
			moves53.setNumberPieces(5);
			movesRepository.save(moves53);
			Moves moves54 = new Moves();
			moves54.setId(Long.valueOf(i));
			i++;
			moves54.setMoves("fb");
			moves54.setClassSet(".threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom");
			moves54.setNumberPieces(6);
			movesRepository.save(moves54);
			Moves moves55 = new Moves();
			moves55.setId(Long.valueOf(i));
			i++;
			moves55.setMoves("fb");
			moves55.setClassSet(".threePiecesSg-e,.threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a");
			moves55.setNumberPieces(7);
			movesRepository.save(moves55);
			Moves moves56 = new Moves();
			moves56.setId(Long.valueOf(i));
			i++;
			moves56.setMoves("eb");
			moves56.setClassSet(".threePiecesSg-d");
			moves56.setNumberPieces(1);
			movesRepository.save(moves56);
			Moves moves57 = new Moves();
			moves57.setId(Long.valueOf(i));
			i++;
			moves57.setMoves("eb");
			moves57.setClassSet(".threePiecesSg-d,.threePiecesSg-c");
			moves57.setNumberPieces(2);
			movesRepository.save(moves57);
			Moves moves58 = new Moves();
			moves58.setId(Long.valueOf(i));
			i++;
			moves58.setMoves("eb");
			moves58.setClassSet(".threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b");
			moves58.setNumberPieces(3);
			movesRepository.save(moves58);
			Moves moves59 = new Moves();
			moves59.setId(Long.valueOf(i));
			i++;
			moves59.setMoves("eb");
			moves59.setClassSet(".threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a");
			moves59.setNumberPieces(4);
			movesRepository.save(moves59);
			Moves moves60 = new Moves();
			moves60.setId(Long.valueOf(i));
			i++;
			moves60.setMoves("eb");
			moves60.setClassSet(".threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom");
			moves60.setNumberPieces(5);
			movesRepository.save(moves60);
			Moves moves61 = new Moves();
			moves61.setId(Long.valueOf(i));
			i++;
			moves61.setMoves("eb");
			moves61.setClassSet(".threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a");
			moves61.setNumberPieces(6);
			movesRepository.save(moves61);
			Moves moves62 = new Moves();
			moves62.setId(Long.valueOf(i));
			i++;
			moves62.setMoves("eb");
			moves62.setClassSet(".threePiecesSg-d,.threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b");
			moves62.setNumberPieces(7);
			movesRepository.save(moves62);
			Moves moves63 = new Moves();
			moves63.setId(Long.valueOf(i));
			i++;
			moves63.setMoves("db");
			moves63.setClassSet(".threePiecesSg-c");
			moves63.setNumberPieces(1);
			movesRepository.save(moves63);
			Moves moves64 = new Moves();
			moves64.setId(Long.valueOf(i));
			i++;
			moves64.setMoves("db");
			moves64.setClassSet(".threePiecesSg-c,.threePiecesSg-b");
			moves64.setNumberPieces(2);
			movesRepository.save(moves64);
			Moves moves65 = new Moves();
			moves65.setId(Long.valueOf(i));
			i++;
			moves65.setMoves("db");
			moves65.setClassSet(".threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a");
			moves65.setNumberPieces(3);
			movesRepository.save(moves65);
			Moves moves66 = new Moves();
			moves66.setId(Long.valueOf(i));
			i++;
			moves66.setMoves("db");
			moves66.setClassSet(".threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom");
			moves66.setNumberPieces(4);
			movesRepository.save(moves66);
			Moves moves67 = new Moves();
			moves67.setId(Long.valueOf(i));
			i++;
			moves67.setMoves("db");
			moves67.setClassSet(".threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a");
			moves67.setNumberPieces(5);
			movesRepository.save(moves67);
			Moves moves68 = new Moves();
			moves68.setId(Long.valueOf(i));
			i++;
			moves68.setMoves("db");
			moves68.setClassSet(".threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b");
			moves68.setNumberPieces(6);
			movesRepository.save(moves68);
			Moves moves69 = new Moves();
			moves69.setId(Long.valueOf(i));
			i++;
			moves69.setMoves("db");
			moves69.setClassSet(".threePiecesSg-c,.threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c");
			moves69.setNumberPieces(7);
			movesRepository.save(moves69);
			Moves moves70 = new Moves();
			moves70.setId(Long.valueOf(i));
			i++;
			moves70.setMoves("cb");
			moves70.setClassSet(".threePiecesSg-b");
			moves70.setNumberPieces(1);
			movesRepository.save(moves70);
			Moves moves71 = new Moves();
			moves71.setId(Long.valueOf(i));
			i++;
			moves71.setMoves("cb");
			moves71.setClassSet(".threePiecesSg-b,.threePiecesSg-a");
			moves71.setNumberPieces(2);
			movesRepository.save(moves71);
			Moves moves72 = new Moves();
			moves72.setId(Long.valueOf(i));
			i++;
			moves72.setMoves("cb");
			moves72.setClassSet(".threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom");
			moves72.setNumberPieces(3);
			movesRepository.save(moves72);
			Moves moves73 = new Moves();
			moves73.setId(Long.valueOf(i));
			i++;
			moves73.setMoves("cb");
			moves73.setClassSet(".threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a");
			moves73.setNumberPieces(4);
			movesRepository.save(moves73);
			Moves moves74 = new Moves();
			moves74.setId(Long.valueOf(i));
			i++;
			moves74.setMoves("cb");
			moves74.setClassSet(".threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b");
			moves74.setNumberPieces(5);
			movesRepository.save(moves74);
			Moves moves75 = new Moves();
			moves75.setId(Long.valueOf(i));
			i++;
			moves75.setMoves("cb");
			moves75.setClassSet(".threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c");
			moves75.setNumberPieces(6);
			movesRepository.save(moves75);
			Moves moves76 = new Moves();
			moves76.setId(Long.valueOf(i));
			i++;
			moves76.setMoves("cb");
			moves76.setClassSet(".threePiecesSg-b,.threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d");
			moves76.setNumberPieces(7);
			movesRepository.save(moves76);
			Moves moves77 = new Moves();
			moves77.setId(Long.valueOf(i));
			i++;
			moves77.setMoves("bb");
			moves77.setClassSet(".threePiecesSg-a");
			moves77.setNumberPieces(1);
			movesRepository.save(moves77);
			Moves moves78 = new Moves();
			moves78.setId(Long.valueOf(i));
			i++;
			moves78.setMoves("bb");
			moves78.setClassSet(".threePiecesSg-a,.threePiecesOsg-f.bottom");
			moves78.setNumberPieces(2);
			movesRepository.save(moves78);
			Moves moves79 = new Moves();
			moves79.setId(Long.valueOf(i));
			i++;
			moves79.setMoves("bb");
			moves79.setClassSet(".threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a");
			moves79.setNumberPieces(3);
			movesRepository.save(moves79);
			Moves moves80 = new Moves();
			moves80.setId(Long.valueOf(i));
			i++;
			moves80.setMoves("bb");
			moves80.setClassSet(".threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b");
			moves80.setNumberPieces(4);
			movesRepository.save(moves80);
			Moves moves81 = new Moves();
			moves81.setId(Long.valueOf(i));
			i++;
			moves81.setMoves("bb");
			moves81.setClassSet(".threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c");
			moves81.setNumberPieces(5);
			movesRepository.save(moves81);
			Moves moves82 = new Moves();
			moves82.setId(Long.valueOf(i));
			i++;
			moves82.setMoves("bb");
			moves82.setClassSet(".threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d");
			moves82.setNumberPieces(6);
			movesRepository.save(moves82);
			Moves moves83 = new Moves();
			moves83.setId(Long.valueOf(i));
			i++;
			moves83.setMoves("bb");
			moves83.setClassSet(".threePiecesSg-a,.threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e");
			moves83.setNumberPieces(7);
			movesRepository.save(moves83);
			Moves moves84 = new Moves();
			moves84.setId(Long.valueOf(i));
			i++;
			moves84.setMoves("ab");
			moves84.setClassSet(".threePiecesOsg-f.bottom");
			moves84.setNumberPieces(1);
			movesRepository.save(moves84);
			Moves moves85 = new Moves();
			moves85.setId(Long.valueOf(i));
			i++;
			moves85.setMoves("ab");
			moves85.setClassSet(".threePiecesOsg-f.bottom,.threePiecesBg-a");
			moves85.setNumberPieces(2);
			movesRepository.save(moves85);
			Moves moves86 = new Moves();
			moves86.setId(Long.valueOf(i));
			i++;
			moves86.setMoves("ab");
			moves86.setClassSet(".threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b");
			moves86.setNumberPieces(3);
			movesRepository.save(moves86);
			Moves moves87 = new Moves();
			moves87.setId(Long.valueOf(i));
			i++;
			moves87.setMoves("ab");
			moves87.setClassSet(".threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c");
			moves87.setNumberPieces(4);
			movesRepository.save(moves87);
			Moves moves88 = new Moves();
			moves88.setId(Long.valueOf(i));
			i++;
			moves88.setMoves("ab");
			moves88.setClassSet(".threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d");
			moves88.setNumberPieces(5);
			movesRepository.save(moves88);
			Moves moves89 = new Moves();
			moves89.setId(Long.valueOf(i));
			i++;
			moves89.setMoves("ab");
			moves89.setClassSet(".threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e");
			moves89.setNumberPieces(6);
			movesRepository.save(moves89);
			Moves moves90 = new Moves();
			moves90.setId(Long.valueOf(i));
			i++;
			moves90.setMoves("ab");
			moves90.setClassSet(".threePiecesOsg-f.bottom,.threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f");
			moves90.setNumberPieces(7);
			movesRepository.save(moves90);
			Moves moves91 = new Moves();
			moves91.setId(Long.valueOf(i));
			i++;
			moves91.setMoves("lr");
			moves91.setClassSet(".threePiecesBg-a");
			moves91.setNumberPieces(1);
			movesRepository.save(moves91);
			Moves moves92 = new Moves();
			moves92.setId(Long.valueOf(i));
			i++;
			moves92.setMoves("lr");
			moves92.setClassSet(".threePiecesBg-a,.threePiecesBg-b");
			moves92.setNumberPieces(2);
			movesRepository.save(moves92);
			Moves moves93 = new Moves();
			moves93.setId(Long.valueOf(i));
			i++;
			moves93.setMoves("lr");
			moves93.setClassSet(".threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c");
			moves93.setNumberPieces(3);
			movesRepository.save(moves93);
			Moves moves94 = new Moves();
			moves94.setId(Long.valueOf(i));
			i++;
			moves94.setMoves("lr");
			moves94.setClassSet(".threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d");
			moves94.setNumberPieces(4);
			movesRepository.save(moves94);
			Moves moves95 = new Moves();
			moves95.setId(Long.valueOf(i));
			i++;
			moves95.setMoves("lr");
			moves95.setClassSet(".threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e");
			moves95.setNumberPieces(5);
			movesRepository.save(moves95);
			Moves moves96 = new Moves();
			moves96.setId(Long.valueOf(i));
			i++;
			moves96.setMoves("lr");
			moves96.setClassSet(".threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f");
			moves96.setNumberPieces(6);
			movesRepository.save(moves96);
			Moves moves97 = new Moves();
			moves97.setId(Long.valueOf(i));
			i++;
			moves97.setMoves("lr");
			moves97.setClassSet(".threePiecesBg-a,.threePiecesBg-b,.threePiecesBg-c,.threePiecesBg-d,.threePiecesBg-e,.threePiecesBg-f,.threePiecesOsg-f.bottom");
			moves97.setNumberPieces(7);
			movesRepository.save(moves97);
		//log.info("Finished with initialize sample data...");
	}
}
